 Time to read keyword file =  0.298 seconds
Warning -Duplicate keyword: PART input with ID=1 
  Warning occurs in file D:\Modified_Wing\Scripts\WingLattice_v2.k
Last one will be used
Warning -Duplicate keyword: MAT input with ID=1 
  Warning occurs in file D:\Modified_Wing\Scripts\WingLattice_v2.k
Last one will be used
Warning -Duplicate keyword: SECTION input with ID=1 
  Warning occurs in file D:\Modified_Wing\Scripts\WingLattice_v2.k
Last one will be used
Message 0
